[package]
name = "scooper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tesseract = "0.12.0"
image = "0.24.5"
clap = { version = "4.0.32", features = ["derive"] }
